name: flutter_html_to_pdf_example
description: Demonstrates how to use the flutter_html_to_pdf plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15

  cupertino_icons: ^1.0.2
  flutter_html_to_pdf:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
