name: flutter_html_to_pdf
description: Flutter plugin for generating PDF documents from HTML code templates
version: 0.7.0
homepage: https://github.com/originoss/flutter_html_to_pdf

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.afur.flutter_html_to_pdf
        pluginClass: FlutterHtmlToPdfPlugin
      ios:
        pluginClass: FlutterHtmlToPdfPlugin

